stages:
  - install
  - test
  - build
  - remote
  - deploy_dependencies
  - deploy_hooks

dependencies:
  stage: install
  script:
    - yarn install
    - composer install
  artifacts:
    expire_in: 35 mins
    paths:
      - node_modules/
      - vendor

test:
  stage: test
  script:
    - php bin/phpunit
  dependencies:
    - dependencies

build_prod_front:
  stage: build
  script:
    - yarn build
  artifacts:
    expire_in: 35 mins
    paths:
      - public/build/
  only:
    - master

remote_prod:
  stage: remote
  script:
    - git checkout -B master origin/master
    - git remote remove prod
    - git remote add prod ssh://dev@l113301siedqual/home/dev/depot-git/coffeetime.git
  allow_failure: true
  only:
    - master

deploy_dependencies:
  stage: deploy_dependencies
  environment:
    name: production
  script:
    - rsync -e ssh -avz --delete-after public/build/ dev@l113301siedqual:/var/www/html/coffeetime/public/build/
    - rsync -e ssh --delete-after --recursive vendor/ dev@l113301siedqual:/var/www/html/coffeetime/vendor/
  only:
    - master
  dependencies:
    - build_prod_front
    - dependencies

deploy_prod_hooks:
  stage: deploy_hooks
  environment:
    name: production
  script:
    - git push prod HEAD:master --force
  only:
    - master